version: '3.8'

services:
  frontend:
    container_name: frontend
    image: animesh0406/fullstack-ui-2
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

  backend:
    container_name: backend
    image: animesh0406/fullstack-back-2
    ports:
      - '4006:4006'
